---
message: "hello, spring cloud -unknown"

service:
  message: Hello World

---

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    
eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true   
    fetch-registry: false
    register-with-eureka: false

ribbon:
  eureka:
    enabled: true              
    
message: "hello, spring cloud default -test"  

---
spring:
  profiles: local
  cloud:
    gateway:
      enabled: true
    kubernetes:
      ribbon.enabled: false
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    lease-expiration-duration-in-seconds: 10      
  instance:
    preferIpAddress: true   
       
ribbon:
  eureka:
    enabled: true

message: "hello, spring cloud -local"

---
spring:
  profiles: local-h2
  cloud:
    gateway:
      enabled: true
    kubernetes:
      ribbon.enabled: false

      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    lease-expiration-duration-in-seconds: 10      
  instance:
    preferIpAddress: true   
       
ribbon:
  eureka:
    enabled: true

message: "hello, spring cloud -local"

---
spring:
  profiles: dock-local
  cloud:
    gateway:
      enabled: true
    kubernetes:
      ribbon.enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://172.19.0.31:8761/eureka

ribbon:
  eureka:
    enabled: true
    
message: "hello, spring cloud -dock-local"

---

spring:
  profiles: dev

message: "hello, spring cloud -dev"

---

spring:
  profiles: prd
  
  
message: "hello, spring cloud -prd"

