---
eureka:
  instance:
    prefer-ip-address: true
      ip-address: 111.0.0.1                

message: "hello, spring cloud -unknown"
        
---
spring:
  profiles: local
  cloud:
    gateway:
      enabled: true
    kubernetes:
      ribbon.enabled: false

eureka:
  instance:
    prefer-ip-address: true
      ip-address: 127.0.0.1                

ribbon:
  eureka:
    enabled: false

message: "hello, spring cloud -local"

---
spring:
  profiles: dock-local

message: "hello, spring cloud -dock-local"

---

spring:
  profiles: dev

message: "hello, spring cloud -dev"

---

spring:
  profiles: prd
  
  
message: "hello, spring cloud -prd"

