---
    
message: "hello, spring cloud datacenter -default"


---        
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/datacenter
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true      
  
server:
  port: 10000
---        
spring:
  profiles: local-dock
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.10.1:3306/datacenter
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true      
  
server:
  port: 10000
---    
spring:
  profiles: local-h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:datacenter
    username: sa
    password: 
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true      
  
server:
  port: 10000


message: "hello, spring cloud datacenter -local"
---
spring:
  profiles: local2
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/datacenter
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true 
        
server:
  port: 10000

message: "hello, spring cloud datacenter -local2"

---
spring:
  profiles: local3
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/datacenter
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true  
        
server:
  port: 10000

message: "hello, spring cloud datacenter -local3"


---
spring:
  profiles: dock-local

message: "hello, spring cloud -local"

---

spring:
  profiles: dev

message: "hello, spring cloud -dev"

---

spring:
  profiles: prd

message: "hello, spring cloud -prd"
