---
message: "hello, spring cloud game api -default"

---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/game
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true  
  
server:
  port: 9001


message: "hello, spring cloud game api -local"
---
spring:
  profiles: local-h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:datacenter
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

server:
  port: 9001


message: "hello, spring cloud game api -local-2"
---
spring:
  profiles: dock-local

message: "hello, spring cloud -dock-local"

---

spring:
  profiles: dev

message: "hello, spring cloud -dev"

---

spring:
  profiles: prd

message: "hello, spring cloud -prd"
