---
message: "hello, spring cloud -default"

---
spring:
  profiles: local
  
server:
  port: 9000

eureka:
    instance:
        prefer-ip-address: true
        ip-address: 127.0.0.1

message: "hello, spring cloud -local"
---
spring:
  profiles: local2
  
server:
  port: 9001

eureka:
    instance:
        prefer-ip-address: true
        ip-address: 127.0.0.1

message: "hello, spring cloud -local"

---
spring:
  profiles: dock-local

message: "hello, spring cloud -local"

---

spring:
  profiles: dev

message: "hello, spring cloud -dev"

---

spring:
  profiles: production

message: "hello, spring cloud -production"
