---
message: "hello, spring cloud lobby api -default"

---
spring:
  profiles: local
  
server:
  port: 9000


message: "hello, spring cloud lobby api -local"
---
spring:
  profiles: local2
  
server:
  port: 9100

message: "hello, spring cloud lobby api -local2"

---
spring:
  profiles: dock-local

message: "hello, spring cloud lobby api -dock-local"

---

spring:
  profiles: dev

message: "hello, spring cloud lobby api -dev"

---

spring:
  profiles: prd

message: "hello, spring cloud lobby api -prd"
