---
message: "hello, spring cloud lobby api -default"

---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/lobby
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true   
  
  
server:
  port: 9200


message: "hello, spring cloud lobby api -local"
---
spring:
  profiles: local2
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/lobby
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true 
  
server:
  port: 9201

message: "hello, spring cloud lobby api -local2"

---
spring:
  profiles: local-h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:lobby
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

server:
  port: 9200


message: "hello, spring cloud lobby api -local-h3"
---
spring:
  profiles: local-h3
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:lobby2
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

server:
  port: 9201


message: "hello, spring cloud lobby api2 -local-h3"
---


spring:
  profiles: dock-local

message: "hello, spring cloud lobby api -dock-local"

---

spring:
  profiles: dev

message: "hello, spring cloud lobby api -dev"

---

spring:
  profiles: prd

message: "hello, spring cloud lobby api -prd"
